version: 2
sources:
- name: cser_kidscanseq
  schema: main
  tables:
  - name: cser_kidscanseq_anvil_dataset
    description: Source table for cser_kidscanseq_anvil_dataset.
    columns:
    - name: dataset_id
      description: '{{ doc("cser_kidscanseq_anvil_dataset_dataset_id") }}'
    - name: consent_group
      description: '{{ doc("cser_kidscanseq_anvil_dataset_consent_group") }}'
    - name: data_use_permission
      description: '{{ doc("cser_kidscanseq_anvil_dataset_data_use_permission") }}'
    - name: owner
      description: '{{ doc("cser_kidscanseq_anvil_dataset_owner") }}'
    - name: principal_investigator
      description: '{{ doc("cser_kidscanseq_anvil_dataset_principal_investigator")
        }}'
    - name: registered_identifier
      description: '{{ doc("cser_kidscanseq_anvil_dataset_registered_identifier")
        }}'
    - name: title
      description: '{{ doc("cser_kidscanseq_anvil_dataset_title") }}'
    - name: data_modality
      description: '{{ doc("cser_kidscanseq_anvil_dataset_data_modality") }}'
    - name: source_datarepo_row_ids
      description: '{{ doc("cser_kidscanseq_anvil_dataset_source_datarepo_row_ids")
        }}'
  - name: cser_kidscanseq_file_inventory
    description: Source table for cser_kidscanseq_file_inventory.
    columns:
    - name: file_id
      description: '{{ doc("cser_kidscanseq_file_inventory_file_id") }}'
    - name: name
      description: '{{ doc("cser_kidscanseq_file_inventory_name") }}'
    - name: path
      description: '{{ doc("cser_kidscanseq_file_inventory_path") }}'
    - name: uri
      description: '{{ doc("cser_kidscanseq_file_inventory_uri") }}'
    - name: content_type
      description: '{{ doc("cser_kidscanseq_file_inventory_content_type") }}'
    - name: full_extension
      description: '{{ doc("cser_kidscanseq_file_inventory_full_extension") }}'
    - name: size_in_bytes
      description: '{{ doc("cser_kidscanseq_file_inventory_size_in_bytes") }}'
    - name: crc32c
      description: '{{ doc("cser_kidscanseq_file_inventory_crc32c") }}'
    - name: md5_hash
      description: '{{ doc("cser_kidscanseq_file_inventory_md5_hash") }}'
    - name: file_ref
      description: '{{ doc("cser_kidscanseq_file_inventory_file_ref") }}'
    - name: ingest_provenance
      description: '{{ doc("cser_kidscanseq_file_inventory_ingest_provenance") }}'
  - name: cser_kidscanseq_sample
    description: Source table for cser_kidscanseq_sample.
    columns:
    - name: sample_id
      description: '{{ doc("cser_kidscanseq_sample_sample_id") }}'
    - name: body_site
      description: '{{ doc("cser_kidscanseq_sample_body_site") }}'
    - name: dbgap_sample_id
      description: '{{ doc("cser_kidscanseq_sample_dbgap_sample_id") }}'
    - name: is_tumor
      description: '{{ doc("cser_kidscanseq_sample_is_tumor") }}'
    - name: primary_metastatic_tumor
      description: '{{ doc("cser_kidscanseq_sample_primary_metastatic_tumor") }}'
    - name: primary_tumor_location
      description: '{{ doc("cser_kidscanseq_sample_primary_tumor_location") }}'
    - name: sample_source
      description: '{{ doc("cser_kidscanseq_sample_sample_source") }}'
    - name: subject_id
      description: '{{ doc("cser_kidscanseq_sample_subject_id") }}'
    - name: subject_id_local
      description: '{{ doc("cser_kidscanseq_sample_subject_id_local") }}'
    - name: submitter_id
      description: '{{ doc("cser_kidscanseq_sample_submitter_id") }}'
    - name: tissue_affected_status
      description: '{{ doc("cser_kidscanseq_sample_tissue_affected_status") }}'
    - name: tumor_grade
      description: '{{ doc("cser_kidscanseq_sample_tumor_grade") }}'
    - name: tumor_stage
      description: '{{ doc("cser_kidscanseq_sample_tumor_stage") }}'
    - name: tumor_treatment
      description: '{{ doc("cser_kidscanseq_sample_tumor_treatment") }}'
    - name: ingest_provenance
      description: '{{ doc("cser_kidscanseq_sample_ingest_provenance") }}'
  - name: cser_kidscanseq_sequencing
    description: Source table for cser_kidscanseq_sequencing.
    columns:
    - name: sequencing_id
      description: '{{ doc("cser_kidscanseq_sequencing_sequencing_id") }}'
    - name: alignment_method
      description: '{{ doc("cser_kidscanseq_sequencing_alignment_method") }}'
    - name: analyte_type
      description: '{{ doc("cser_kidscanseq_sequencing_analyte_type") }}'
    - name: capture_region_bed_file
      description: '{{ doc("cser_kidscanseq_sequencing_capture_region_bed_file") }}'
    - name: data_processing_pipeline
      description: '{{ doc("cser_kidscanseq_sequencing_data_processing_pipeline")
        }}'
    - name: date_data_generation
      description: '{{ doc("cser_kidscanseq_sequencing_date_data_generation") }}'
    - name: exome_capture_platform
      description: '{{ doc("cser_kidscanseq_sequencing_exome_capture_platform") }}'
    - name: functional_equivalence_standard
      description: '{{ doc("cser_kidscanseq_sequencing_functional_equivalence_standard")
        }}'
    - name: index_file
      description: '{{ doc("cser_kidscanseq_sequencing_index_file") }}'
    - name: library_prep_kit_method
      description: '{{ doc("cser_kidscanseq_sequencing_library_prep_kit_method") }}'
    - name: number_of_independent_libraries
      description: '{{ doc("cser_kidscanseq_sequencing_number_of_independent_libraries")
        }}'
    - name: read_length
      description: '{{ doc("cser_kidscanseq_sequencing_read_length") }}'
    - name: reference_genome_build
      description: '{{ doc("cser_kidscanseq_sequencing_reference_genome_build") }}'
    - name: sample_id
      description: '{{ doc("cser_kidscanseq_sequencing_sample_id") }}'
    - name: seq_filename
      description: '{{ doc("cser_kidscanseq_sequencing_seq_filename") }}'
    - name: sequencer_id
      description: '{{ doc("cser_kidscanseq_sequencing_sequencer_id") }}'
    - name: sequencing_assay
      description: '{{ doc("cser_kidscanseq_sequencing_sequencing_assay") }}'
    - name: sequencing_platform
      description: '{{ doc("cser_kidscanseq_sequencing_sequencing_platform") }}'
    - name: target_depth
      description: '{{ doc("cser_kidscanseq_sequencing_target_depth") }}'
    - name: target_insert_size
      description: '{{ doc("cser_kidscanseq_sequencing_target_insert_size") }}'
    - name: ingest_provenance
      description: '{{ doc("cser_kidscanseq_sequencing_ingest_provenance") }}'
    - name: sequencing_id_fileref
      description: '{{ doc("cser_kidscanseq_sequencing_sequencing_id_fileref") }}'
  - name: cser_kidscanseq_subject
    description: Source table for cser_kidscanseq_subject.
    columns:
    - name: subject_id
      description: '{{ doc("cser_kidscanseq_subject_subject_id") }}'
    - name: dbgap_study_id
      description: '{{ doc("cser_kidscanseq_subject_dbgap_study_id") }}'
    - name: dbgap_submission
      description: '{{ doc("cser_kidscanseq_subject_dbgap_submission") }}'
    - name: disease_id
      description: '{{ doc("cser_kidscanseq_subject_disease_id") }}'
    - name: family_id
      description: '{{ doc("cser_kidscanseq_subject_family_id") }}'
    - name: hpo_absent
      description: '{{ doc("cser_kidscanseq_subject_hpo_absent") }}'
    - name: hpo_present
      description: '{{ doc("cser_kidscanseq_subject_hpo_present") }}'
    - name: maternal_id
      description: '{{ doc("cser_kidscanseq_subject_maternal_id") }}'
    - name: multiple_datasets
      description: '{{ doc("cser_kidscanseq_subject_multiple_datasets") }}'
    - name: paternal_id
      description: '{{ doc("cser_kidscanseq_subject_paternal_id") }}'
    - name: phenotype_group
      description: '{{ doc("cser_kidscanseq_subject_phenotype_group") }}'
    - name: pmids
      description: '{{ doc("cser_kidscanseq_subject_pmids") }}'
    - name: race_ethnicity
      description: '{{ doc("cser_kidscanseq_subject_race_ethnicity") }}'
    - name: sex
      description: '{{ doc("cser_kidscanseq_subject_sex") }}'
    - name: ingest_provenance
      description: '{{ doc("cser_kidscanseq_subject_ingest_provenance") }}'
