name: gregor_test_study
version: 1.0.0
profile: anvil
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
  +schema: gregor_test_study_data
  +materialized: table
  participant:
    gregor_test_study_src_participant:
      +schema: gregor_test_study_data
      +materialized: table
    gregor_test_study_stg_participant:
      +schema: gregor_test_study_data
      +materialized: table
  phenotype:
    gregor_test_study_src_phenotype:
      +schema: gregor_test_study_data
      +materialized: table
    gregor_test_study_stg_phenotype:
      +schema: gregor_test_study_data
      +materialized: table
