name: catalog
version: 1.0.0
profile: anvil_duckdb
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages

vars:
  target_schema: "fallback_schema"
  source_table: "{study_id}_stg_{table_id}" # Fallback table, define a stg table that is being run.
