name: ftd
version: 1.0.0
profile: include
model-paths:
- models
macro-paths:
- macros
clean-targets:
- target
- dbt_packages
models:
  m00m00:
    m00m00_ftd_participant:
      +schema: m00m00_src_data
      +materialized: table
    m00m00_ftd_condition:
      +schema: m00m00_src_data
      +materialized: table
