version: 2
sources:
- name: eMERGEseq
  schema: main
  tables:
  - name: eMERGEseq_Demographics_DS_20200925
    description: Source table for eMERGEseq_Demographics_DS_20200925.
    columns:
    - name: subject_id
      description: '{{ doc("eMERGEseq_Demographics_DS_20200925_subject_id") }}'
    - name: sex
      description: '{{ doc("eMERGEseq_Demographics_DS_20200925_sex") }}'
    - name: decade_birth
      description: '{{ doc("eMERGEseq_Demographics_DS_20200925_decade_birth") }}'
    - name: year_birth
      description: '{{ doc("eMERGEseq_Demographics_DS_20200925_year_birth") }}'
    - name: ethnicity
      description: '{{ doc("eMERGEseq_Demographics_DS_20200925_ethnicity") }}'
    - name: race
      description: '{{ doc("eMERGEseq_Demographics_DS_20200925_race") }}'
  - name: eMERGEseq_Phecode_DS_20200925
    description: Source table for eMERGEseq_Phecode_DS_20200925.
    columns:
    - name: subject_id
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_subject_id") }}'
    - name: PHE_401.1
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_401_1") }}'
    - name: PHE_250.2
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_250_2") }}'
    - name: PHE_272.1
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_272_1") }}'
    - name: PHE_411.4
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_411_4") }}'
    - name: PHE_495
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_495") }}'
    - name: PHE_427.21
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_427_21") }}'
    - name: PHE_530.11
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_530_11") }}'
    - name: PHE_296.22
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_296_22") }}'
    - name: PHE_313.1
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_313_1") }}'
    - name: PHE_244.4
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_244_4") }}'
    - name: PHE_476
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_476") }}'
    - name: PHE_272.11
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_272_11") }}'
    - name: PHE_278.1
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_278_1") }}'
    - name: PHE_174.11
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_174_11") }}'
    - name: PHE_296.2
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_296_2") }}'
    - name: PHE_306
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_306") }}'
    - name: PHE_327.32
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_327_32") }}'
    - name: PHE_313.3
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_313_3") }}'
    - name: PHE_278.11
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_278_11") }}'
    - name: PHE_272.13
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_272_13") }}'
    - name: PHE_587
      description: '{{ doc("eMERGEseq_Phecode_DS_20200925_phe_587") }}'
  - name: eMERGEseq_SampleAttributes_DS_20200925
    description: Source table for eMERGEseq_SampleAttributes_DS_20200925.
    columns:
    - name: sample_id
      description: '{{ doc("eMERGEseq_SampleAttributes_DS_20200925_sample_id") }}'
    - name: analyte_type
      description: '{{ doc("eMERGEseq_SampleAttributes_DS_20200925_analyte_type")
        }}'
    - name: sequencing_center
      description: '{{ doc("eMERGEseq_SampleAttributes_DS_20200925_sequencing_center")
        }}'
  - name: eMERGEseq_SampleSubjectMapping_DS_20200925
    description: Source table for eMERGEseq_SampleSubjectMapping_DS_20200925.
    columns:
    - name: subject_id
      description: '{{ doc("eMERGEseq_SampleSubjectMapping_DS_20200925_subject_id")
        }}'
    - name: sample_id
      description: '{{ doc("eMERGEseq_SampleSubjectMapping_DS_20200925_sample_id")
        }}'
    - name: sample_source
      description: '{{ doc("eMERGEseq_SampleSubjectMapping_DS_20200925_sample_source")
        }}'
  - name: eMERGEseq_SubjectConsent_DS_20201020
    description: Source table for eMERGEseq_SubjectConsent_DS_20201020.
    columns:
    - name: subject_id
      description: '{{ doc("eMERGEseq_SubjectConsent_DS_20201020_subject_id") }}'
    - name: consent
      description: '{{ doc("eMERGEseq_SubjectConsent_DS_20201020_consent") }}'
    - name: subject_source
      description: '{{ doc("eMERGEseq_SubjectConsent_DS_20201020_subject_source")
        }}'
  - name: eMERGEseq_BMI_DS_20200925
    description: Source table for eMERGEseq_BMI_DS_20200925.
    columns:
    - name: subject_id
      description: '{{ doc("eMERGEseq_BMI_DS_20200925_subject_id") }}'
    - name: age_at_observation
      description: '{{ doc("eMERGEseq_BMI_DS_20200925_age_at_observation") }}'
    - name: weight
      description: '{{ doc("eMERGEseq_BMI_DS_20200925_weight") }}'
    - name: height
      description: '{{ doc("eMERGEseq_BMI_DS_20200925_height") }}'
    - name: body_mass_index
      description: '{{ doc("eMERGEseq_BMI_DS_20200925_body_mass_index") }}'
    - name: visit_number
      description: '{{ doc("eMERGEseq_BMI_DS_20200925_visit_number") }}'
  - name: eMERGEseq_Pedigree_DS_20200925
    description: Source table for eMERGEseq_Pedigree_DS_20200925.
    columns:
    - name: family_id
      description: '{{ doc("eMERGEseq_Pedigree_DS_20200925_family_id") }}'
    - name: subject_id
      description: '{{ doc("eMERGEseq_Pedigree_DS_20200925_subject_id") }}'
    - name: mother
      description: '{{ doc("eMERGEseq_Pedigree_DS_20200925_mother") }}'
    - name: father
      description: '{{ doc("eMERGEseq_Pedigree_DS_20200925_father") }}'
    - name: sex
      description: '{{ doc("eMERGEseq_Pedigree_DS_20200925_sex") }}'
    - name: mz_twin_id
      description: '{{ doc("eMERGEseq_Pedigree_DS_20200925_mz_twin_id") }}'
