version: 2
sources:
- name: cmg_bh
  schema: main
  tables:
  - name: sample
    description: Source table for sample.
    columns:
    - name: sample_id
      description: '{{ doc("sample_sample_id") }}'
    - name: bai
      description: '{{ doc("sample_bai") }}'
    - name: bai_md5
      description: '{{ doc("sample_bai_md5") }}'
    - name: bam
      description: '{{ doc("sample_bam") }}'
    - name: bam_md5
      description: '{{ doc("sample_bam_md5") }}'
    - name: subject_id
      description: '{{ doc("sample_subject_id") }}'
    - name: crai
      description: '{{ doc("sample_crai") }}'
    - name: cram_md5
      description: '{{ doc("sample_cram_md5") }}'
    - name: ingest_provenance
      description: '{{ doc("sample_ingest_provenance") }}'
    - name: Submission_Batch
      description: '{{ doc("sample_submission_batch") }}'
    - name: dbgap_sample_id
      description: '{{ doc("sample_dbgap_sample_id") }}'
    - name: sample_provider
      description: '{{ doc("sample_sample_provider") }}'
    - name: sample_source
      description: '{{ doc("sample_sample_source") }}'
    - name: tissue_affected_status
      description: '{{ doc("sample_tissue_affected_status") }}'
  - name: subject
    description: Source table for subject.
    columns:
    - name: subject_id
      description: '{{ doc("subject_subject_id") }}'
    - name: submission_batch
      description: '{{ doc("subject_submission_batch") }}'
    - name: affected_status
      description: '{{ doc("subject_affected_status") }}'
    - name: ancestry
      description: '{{ doc("subject_ancestry") }}'
    - name: dbgap_study_id
      description: '{{ doc("subject_dbgap_study_id") }}'
    - name: dbgap_submission
      description: '{{ doc("subject_dbgap_submission") }}'
    - name: family_id
      description: '{{ doc("subject_family_id") }}'
    - name: family_relationship
      description: '{{ doc("subject_family_relationship") }}'
    - name: hpo_present
      description: '{{ doc("subject_hpo_present") }}'
    - name: maternal_id
      description: '{{ doc("subject_maternal_id") }}'
    - name: multiple_datasets
      description: '{{ doc("subject_multiple_datasets") }}'
    - name: paternal_id
      description: '{{ doc("subject_paternal_id") }}'
    - name: phenotype_description
      description: '{{ doc("subject_phenotype_description") }}'
    - name: phenotype_group
      description: '{{ doc("subject_phenotype_group") }}'
    - name: project_investigator
      description: '{{ doc("subject_project_investigator") }}'
    - name: sex
      description: '{{ doc("subject_sex") }}'
    - name: solve_state
      description: '{{ doc("subject_solve_state") }}'
    - name: disease_id
      description: '{{ doc("subject_disease_id") }}'
    - name: ancestry_detail
      description: '{{ doc("subject_ancestry_detail") }}'
    - name: hpo_absent
      description: '{{ doc("subject_hpo_absent") }}'
    - name: twin_id
      description: '{{ doc("subject_twin_id") }}'
    - name: ingest_provenance
      description: '{{ doc("subject_ingest_provenance") }}'
