name: GREGoR_R01_HMB_20240208
version: 1.0.0
profile: anvil
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
  +schema: main
  +materialized: table
  participant:
    GREGoR_R01_HMB_20240208_stg_participant:
      +schema: main
      +materialized: table
  phenotype:
    GREGoR_R01_HMB_20240208_stg_phenotype:
      +schema: main
      +materialized: table
