version: 2
sources:
- name: GREGoR_R03_HMB_20250612
  schema: main
  tables:
  - name: GREGoR_R03_HMB_20250612_participant
    description: Source table for GREGoR_R03_HMB_20250612_participant.
    columns:
    - name: participant_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_participant_id") }}'
    - name: affected_status
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_affected_status")
        }}'
    - name: age_at_enrollment
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_age_at_enrollment")
        }}'
    - name: age_at_last_observation
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_age_at_last_observation")
        }}'
    - name: ancestry_detail
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_ancestry_detail")
        }}'
    - name: consent_code
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_consent_code") }}'
    - name: family_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_family_id") }}'
    - name: gregor_center
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_gregor_center") }}'
    - name: internal_project_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_internal_project_id")
        }}'
    - name: maternal_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_maternal_id") }}'
    - name: missing_variant_case
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_missing_variant_case")
        }}'
    - name: paternal_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_paternal_id") }}'
    - name: phenotype_description
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_phenotype_description")
        }}'
    - name: pmid_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_pmid_id") }}'
    - name: prior_testing
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_prior_testing") }}'
    - name: proband_relationship
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_proband_relationship")
        }}'
    - name: proband_relationship_detail
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_proband_relationship_detail")
        }}'
    - name: reported_ethnicity
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_reported_ethnicity")
        }}'
    - name: reported_race
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_reported_race") }}'
    - name: sex
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_sex") }}'
    - name: sex_detail
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_sex_detail") }}'
    - name: solve_status
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_solve_status") }}'
    - name: twin_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_twin_id") }}'
    - name: ingest_provenance
      description: '{{ doc("GREGoR_R03_HMB_20250612_participant_ingest_provenance")
        }}'
  - name: GREGoR_R03_HMB_20250612_phenotype
    description: Source table for GREGoR_R03_HMB_20250612_phenotype.
    columns:
    - name: phenotype_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_phenotype_phenotype_id") }}'
    - name: additional_details
      description: '{{ doc("GREGoR_R03_HMB_20250612_phenotype_additional_details")
        }}'
    - name: additional_modifiers
      description: '{{ doc("GREGoR_R03_HMB_20250612_phenotype_additional_modifiers")
        }}'
    - name: onset_age_range
      description: '{{ doc("GREGoR_R03_HMB_20250612_phenotype_onset_age_range") }}'
    - name: ontology
      description: '{{ doc("GREGoR_R03_HMB_20250612_phenotype_ontology") }}'
    - name: participant_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_phenotype_participant_id") }}'
    - name: presence
      description: '{{ doc("GREGoR_R03_HMB_20250612_phenotype_presence") }}'
    - name: syndromic
      description: '{{ doc("GREGoR_R03_HMB_20250612_phenotype_syndromic") }}'
    - name: term_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_phenotype_term_id") }}'
  - name: GREGoR_R03_HMB_20250612_experiment
    description: Source table for GREGoR_R03_HMB_20250612_experiment.
    columns:
    - name: experiment_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_experiment_experiment_id") }}'
    - name: table_name
      description: '{{ doc("GREGoR_R03_HMB_20250612_experiment_table_name") }}'
    - name: id_in_table
      description: '{{ doc("GREGoR_R03_HMB_20250612_experiment_id_in_table") }}'
    - name: participant_id
      description: '{{ doc("GREGoR_R03_HMB_20250612_experiment_participant_id") }}'
