name: gregor_synthetic
version: 1.0.0
profile: anvil
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
  +schema: main
  +materialized: table
  participant:
    gregor_synthetic_stg_participant:
      +schema: main
      +materialized: table
  phenotype:
    gregor_synthetic_stg_phenotype:
      +schema: main
      +materialized: table
