name: gregor_synthetic
version: 1.0.0
profile: anvil_duckdb
model-paths:
- models
macro-paths:
- macros
seed-paths:
- seeds
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
vars: {}
models:
  gregor_synthetic:
    +schema: main
    +materialized: table
    participant: {}
    phenotype: {}
