version: 2
sources:
- name: GWAS
  schema: main
  tables:
  - name: GWAS_BMI_DS_20201028
    description: Source table for GWAS_BMI_DS_20201028.
    columns:
    - name: subject_id
      description: '{{ doc("GWAS_BMI_DS_20201028_subject_id") }}'
    - name: bmi_observation_age
      description: '{{ doc("GWAS_BMI_DS_20201028_bmi_observation_age") }}'
    - name: weight
      description: '{{ doc("GWAS_BMI_DS_20201028_weight") }}'
    - name: height
      description: '{{ doc("GWAS_BMI_DS_20201028_height") }}'
    - name: body_mass_index
      description: '{{ doc("GWAS_BMI_DS_20201028_body_mass_index") }}'
    - name: visit_number
      description: '{{ doc("GWAS_BMI_DS_20201028_visit_number") }}'
  - name: GWAS_CaseControl_DD_20201027
    description: Source table for GWAS_CaseControl_DD_20201027.
    columns:
    - name: subject_id
      description: '{{ doc("GWAS_CaseControl_DD_20201027_subject_id") }}'
    - name: sex
      description: '{{ doc("GWAS_CaseControl_DD_20201027_sex") }}'
    - name: decade_birth
      description: '{{ doc("GWAS_CaseControl_DD_20201027_decade_birth") }}'
    - name: year_birth
      description: '{{ doc("GWAS_CaseControl_DD_20201027_year_birth") }}'
    - name: ethnicity
      description: '{{ doc("GWAS_CaseControl_DD_20201027_ethnicity") }}'
    - name: race
      description: '{{ doc("GWAS_CaseControl_DD_20201027_race") }}'
    - name: case_control_aaa
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_aaa") }}'
    - name: case_control_acei
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_acei") }}'
    - name: case_control_adhd
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_adhd") }}'
    - name: case_control_amd
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_amd") }}'
    - name: case_control_appendicitis
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_appendicitis")
        }}'
    - name: case_control_asthma
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_asthma") }}'
    - name: case_control_atopicdermatitis
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_atopicdermatitis")
        }}'
    - name: case_control_autism
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_autism") }}'
    - name: case_control_bph
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_bph") }}'
    - name: case_control_caad
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_caad") }}'
    - name: case_control_camrsa
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_camrsa") }}'
    - name: case_control_cataract
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_cataract") }}'
    - name: case_control_cdiff
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_cdiff") }}'
    - name: case_control_childhoodobesity
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_childhoodobesity")
        }}'
    - name: case_control_ckd
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_ckd") }}'
    - name: case_control_ckd_t2d
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_ckd_t2d") }}'
    - name: case_control_ckd_t2d_htn
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_ckd_t2d_htn")
        }}'
    - name: case_control_colonpolyps
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_colonpolyps")
        }}'
    - name: case_control_crf
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_crf") }}'
    - name: case_control_dementia
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_dementia") }}'
    - name: case_control_div
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_div") }}'
    - name: case_control_dr
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_dr") }}'
    - name: case_control_extremeobesity
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_extremeobesity")
        }}'
    - name: case_control_gerd
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_gerd") }}'
    - name: case_control_glaucoma
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_glaucoma") }}'
    - name: case_control_height
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_height") }}'
    - name: case_control_hf
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_hf") }}'
    - name: case_control_hypothyroidism
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_hypothyroidism")
        }}'
    - name: case_control_lipids
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_lipids") }}'
    - name: case_control_ocularhtn
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_ocularhtn")
        }}'
    - name: case_control_pad
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_pad") }}'
    - name: case_control_qrs
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_qrs") }}'
    - name: case_control_rbc
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_rbc") }}'
    - name: case_control_remissiondiabetes
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_remissiondiabetes")
        }}'
    - name: case_control_reshyp
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_reshyp") }}'
    - name: case_control_statinsmace
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_statinsmace")
        }}'
    - name: case_control_t2d
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_t2d") }}'
    - name: case_control_vte
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_vte") }}'
    - name: case_control_wbc
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_wbc") }}'
    - name: case_control_zoster
      description: '{{ doc("GWAS_CaseControl_DD_20201027_case_control_zoster") }}'
  - name: GWAS_Demographics_DS_20201109
    description: Source table for GWAS_Demographics_DS_20201109.
    columns:
    - name: subject_id
      description: '{{ doc("GWAS_Demographics_DS_20201109_subject_id") }}'
    - name: decade_birth
      description: '{{ doc("GWAS_Demographics_DS_20201109_decade_birth") }}'
    - name: year_birth
      description: '{{ doc("GWAS_Demographics_DS_20201109_year_birth") }}'
    - name: sex
      description: '{{ doc("GWAS_Demographics_DS_20201109_sex") }}'
    - name: race
      description: '{{ doc("GWAS_Demographics_DS_20201109_race") }}'
    - name: ethnicity
      description: '{{ doc("GWAS_Demographics_DS_20201109_ethnicity") }}'
  - name: GWAS_Pedigree_DS_20200512
    description: Source table for GWAS_Pedigree_DS_20200512.
    columns:
    - name: family_id
      description: '{{ doc("GWAS_Pedigree_DS_20200512_family_id") }}'
    - name: subject_id
      description: '{{ doc("GWAS_Pedigree_DS_20200512_subject_id") }}'
    - name: mother
      description: '{{ doc("GWAS_Pedigree_DS_20200512_mother") }}'
    - name: father
      description: '{{ doc("GWAS_Pedigree_DS_20200512_father") }}'
    - name: sex
      description: '{{ doc("GWAS_Pedigree_DS_20200512_sex") }}'
    - name: mz_twin_id
      description: '{{ doc("GWAS_Pedigree_DS_20200512_mz_twin_id") }}'
  - name: GWAS_Phecode_DS_20201027
    description: Source table for GWAS_Phecode_DS_20201027.
    columns:
    - name: subject_id
      description: '{{ doc("GWAS_Phecode_DS_20201027_subject_id") }}'
    - name: age_at_observation
      description: '{{ doc("GWAS_Phecode_DS_20201027_age_at_observation") }}'
    - name: icd_code
      description: '{{ doc("GWAS_Phecode_DS_20201027_icd_code") }}'
    - name: icd_flag
      description: '{{ doc("GWAS_Phecode_DS_20201027_icd_flag") }}'
    - name: phecode
      description: '{{ doc("GWAS_Phecode_DS_20201027_phecode") }}'
  - name: GWAS_SampleAttributes_DS_20201027
    description: Source table for GWAS_SampleAttributes_DS_20201027.
    columns:
    - name: sample_id
      description: '{{ doc("GWAS_SampleAttributes_DS_20201027_sample_id") }}'
    - name: analyte_type
      description: '{{ doc("GWAS_SampleAttributes_DS_20201027_analyte_type") }}'
  - name: GWAS_SampleSubjectMapping_DS_20201027
    description: Source table for GWAS_SampleSubjectMapping_DS_20201027.
    columns:
    - name: subject_id
      description: '{{ doc("GWAS_SampleSubjectMapping_DS_20201027_subject_id") }}'
    - name: sample_id
      description: '{{ doc("GWAS_SampleSubjectMapping_DS_20201027_sample_id") }}'
    - name: samp_source
      description: '{{ doc("GWAS_SampleSubjectMapping_DS_20201027_samp_source") }}'
    - name: source_sampid
      description: '{{ doc("GWAS_SampleSubjectMapping_DS_20201027_source_sampid")
        }}'
  - name: GWAS_SubjectConsent_DS_20190813
    description: Source table for GWAS_SubjectConsent_DS_20190813.
    columns:
    - name: subject_id
      description: '{{ doc("GWAS_SubjectConsent_DS_20190813_subject_id") }}'
    - name: consent
      description: '{{ doc("GWAS_SubjectConsent_DS_20190813_consent") }}'
    - name: subject_source
      description: '{{ doc("GWAS_SubjectConsent_DS_20190813_subject_source") }}'
    - name: source_subject_id
      description: '{{ doc("GWAS_SubjectConsent_DS_20190813_source_subject_id") }}'
