name: cser_datasets
version: 1.0.0
profile: anvil
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
  +schema: main
  +materialized: table
  anvil_dataset:
    cser_datasets_stg_anvil_dataset:
      +schema: main
      +materialized: table
  file_inventory:
    cser_datasets_stg_file_inventory:
      +schema: main
      +materialized: table
  sample:
    cser_datasets_stg_sample:
      +schema: main
      +materialized: table
  sequencing:
    cser_datasets_stg_sequencing:
      +schema: main
      +materialized: table
  subject:
    cser_datasets_stg_subject:
      +schema: main
      +materialized: table
