name: PGRNseq
version: 1.0.0
profile: anvil
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
  +schema: main
  +materialized: table
  bmi:
    PGRNseq_stg_bmi:
      +schema: main
      +materialized: table
  demographics:
    PGRNseq_stg_demographics:
      +schema: main
      +materialized: table
  ecg:
    PGRNseq_stg_ecg:
      +schema: main
      +materialized: table
  labs:
    PGRNseq_stg_labs:
      +schema: main
      +materialized: table
  sampleattribution:
    PGRNseq_stg_sampleattribution:
      +schema: main
      +materialized: table
  samplesubjectmapping:
    PGRNseq_stg_samplesubjectmapping:
      +schema: main
      +materialized: table
  subjectconsent:
    PGRNseq_stg_subjectconsent:
      +schema: main
      +materialized: table
