version: 2
sources:
- name: cmg_yale
  schema: main
  tables:
  - name: sample
    description: Source table for sample.
    columns:
    - name: sample_id
      description: '{{ doc("sample_sample_id") }}'
    - name: sample_source
      description: '{{ doc("sample_sample_source") }}'
    - name: sequencing_center
      description: '{{ doc("sample_sequencing_center") }}'
    - name: subject_id
      description: '{{ doc("sample_subject_id") }}'
    - name: ingest_provenance
      description: '{{ doc("sample_ingest_provenance") }}'
    - name: subject_id2
      description: '{{ doc("sample_subject_id2") }}'
    - name: crai
      description: '{{ doc("sample_crai") }}'
    - name: cram
      description: '{{ doc("sample_cram") }}'
  - name: subject
    description: Source table for subject.
    columns:
    - name: subject_id
      description: '{{ doc("subject_subject_id") }}'
    - name: affected_status
      description: '{{ doc("subject_affected_status") }}'
    - name: ancestry
      description: '{{ doc("subject_ancestry") }}'
    - name: ancestry_detail
      description: '{{ doc("subject_ancestry_detail") }}'
    - name: dbgap_submission
      description: '{{ doc("subject_dbgap_submission") }}'
    - name: disease_description
      description: '{{ doc("subject_disease_description") }}'
    - name: family_id
      description: '{{ doc("subject_family_id") }}'
    - name: hpo_present
      description: '{{ doc("subject_hpo_present") }}'
    - name: maternal_id
      description: '{{ doc("subject_maternal_id") }}'
    - name: multiple_datasets
      description: '{{ doc("subject_multiple_datasets") }}'
    - name: paternal_id
      description: '{{ doc("subject_paternal_id") }}'
    - name: proband_relationship
      description: '{{ doc("subject_proband_relationship") }}'
    - name: project_id
      description: '{{ doc("subject_project_id") }}'
    - name: dbgap_study_id
      description: '{{ doc("subject_dbgap_study_id") }}'
    - name: sex
      description: '{{ doc("subject_sex") }}'
    - name: ingest_provenance
      description: '{{ doc("subject_ingest_provenance") }}'
    - name: disease_id
      description: '{{ doc("subject_disease_id") }}'
    - name: sample_id
      description: '{{ doc("subject_sample_id") }}'
  - name: anvil_dataset
    description: Source table for anvil_dataset.
    columns:
    - name: consent_group
      description: '{{ doc("anvil_dataset_consent_group") }}'
    - name: data_use_permission
      description: '{{ doc("anvil_dataset_data_use_permission") }}'
    - name: owner
      description: '{{ doc("anvil_dataset_owner") }}'
    - name: principal_investigator
      description: '{{ doc("anvil_dataset_principal_investigator") }}'
    - name: registered_identifier
      description: '{{ doc("anvil_dataset_registered_identifier") }}'
    - name: title
      description: '{{ doc("anvil_dataset_title") }}'
    - name: data_modality
      description: '{{ doc("anvil_dataset_data_modality") }}'
    - name: source_datarepo_row_ids
      description: '{{ doc("anvil_dataset_source_datarepo_row_ids") }}'
  - name: sequencing
    description: Source table for sequencing.
    columns:
    - name: sequencing_id
      description: '{{ doc("sequencing_sequencing_id") }}'
    - name: alignment_method
      description: '{{ doc("sequencing_alignment_method") }}'
    - name: analyte_type
      description: '{{ doc("sequencing_analyte_type") }}'
    - name: data_processing_pipeline
      description: '{{ doc("sequencing_data_processing_pipeline") }}'
    - name: date_data_generation
      description: '{{ doc("sequencing_date_data_generation") }}'
    - name: functional_equivalence_standard
      description: '{{ doc("sequencing_functional_equivalence_standard") }}'
    - name: library_prep_kit_method
      description: '{{ doc("sequencing_library_prep_kit_method") }}'
    - name: reference_genome_build
      description: '{{ doc("sequencing_reference_genome_build") }}'
    - name: sample_id
      description: '{{ doc("sequencing_sample_id") }}'
    - name: seq_filename
      description: '{{ doc("sequencing_seq_filename") }}'
    - name: sequencing_assay
      description: '{{ doc("sequencing_sequencing_assay") }}'
    - name: ingest_provenance
      description: '{{ doc("sequencing_ingest_provenance") }}'
    - name: sequencing_id_fileref
      description: '{{ doc("sequencing_sequencing_id_fileref") }}'
    - name: capture_region_bed_file
      description: '{{ doc("sequencing_capture_region_bed_file") }}'
    - name: exome_capture_platform
      description: '{{ doc("sequencing_exome_capture_platform") }}'
  - name: family
    description: Source table for family.
    columns:
    - name: family_id
      description: '{{ doc("family_family_id") }}'
    - name: consanguinity
      description: '{{ doc("family_consanguinity") }}'
    - name: ingest_provenance
      description: '{{ doc("family_ingest_provenance") }}'
  - name: file_inventory
    description: Source table for file_inventory.
    columns:
    - name: file_id
      description: '{{ doc("file_inventory_file_id") }}'
    - name: name
      description: '{{ doc("file_inventory_name") }}'
    - name: path
      description: '{{ doc("file_inventory_path") }}'
    - name: uri
      description: '{{ doc("file_inventory_uri") }}'
    - name: content_type
      description: '{{ doc("file_inventory_content_type") }}'
    - name: full_extension
      description: '{{ doc("file_inventory_full_extension") }}'
    - name: size_in_bytes
      description: '{{ doc("file_inventory_size_in_bytes") }}'
    - name: crc32c
      description: '{{ doc("file_inventory_crc32c") }}'
    - name: md5_hash
      description: '{{ doc("file_inventory_md5_hash") }}'
    - name: file_ref
      description: '{{ doc("file_inventory_file_ref") }}'
    - name: ingest_provenance
      description: '{{ doc("file_inventory_ingest_provenance") }}'
