name: GWAS
version: 1.0.0
profile: anvil
model-paths:
- models
macro-paths:
- macros
snapshot-paths:
- snapshots
clean-targets:
- target
- dbt_packages
models:
  +schema: main
  +materialized: table
  bmi:
    GWAS_stg_bmi:
      +schema: main
      +materialized: table
  casecontrol:
    GWAS_stg_casecontrol:
      +schema: main
      +materialized: table
  demographics:
    GWAS_stg_demographics:
      +schema: main
      +materialized: table
  pedigree:
    GWAS_stg_pedigree:
      +schema: main
      +materialized: table
  phecode:
    GWAS_stg_phecode:
      +schema: main
      +materialized: table
  sampleattributes:
    GWAS_stg_sampleattributes:
      +schema: main
      +materialized: table
  samplesubjectmapping:
    GWAS_stg_samplesubjectmapping:
      +schema: main
      +materialized: table
  subjectconsent:
    GWAS_stg_subjectconsent:
      +schema: main
      +materialized: table
