name: ftd
version: 1.0.0
profile: anvil
model-paths:
- models
macro-paths:
- macros
clean-targets:
- target
- dbt_packages
models:
  gregor_test_study:
    gregor_test_study_ftd_phenotype:
      +schema: gregor_test_study_ftd_data
      +materialized: table
    gregor_test_study_ftd_participant:
      +schema: gregor_test_study_ftd_data
      +materialized: table
