version: 2
sources:
- name: PGRNseq
  schema: main
  tables:
  - name: PGRNseq_BMI_DS_2015
    description: Source table for PGRNseq_BMI_DS_2015.
    columns:
    - name: subject_id
      description: '{{ doc("PGRNseq_BMI_DS_2015_subject_id") }}'
    - name: weight
      description: '{{ doc("PGRNseq_BMI_DS_2015_weight") }}'
    - name: height
      description: '{{ doc("PGRNseq_BMI_DS_2015_height") }}'
    - name: body_mass_index
      description: '{{ doc("PGRNseq_BMI_DS_2015_body_mass_index") }}'
    - name: age_observation
      description: '{{ doc("PGRNseq_BMI_DS_2015_age_observation") }}'
    - name: visit_number
      description: '{{ doc("PGRNseq_BMI_DS_2015_visit_number") }}'
  - name: PGRNseq_Demographics_DS_2015
    description: Source table for PGRNseq_Demographics_DS_2015.
    columns:
    - name: subject_id
      description: '{{ doc("PGRNseq_Demographics_DS_2015_subject_id") }}'
    - name: sex
      description: '{{ doc("PGRNseq_Demographics_DS_2015_sex") }}'
    - name: decade_birth
      description: '{{ doc("PGRNseq_Demographics_DS_2015_decade_birth") }}'
    - name: year_birth
      description: '{{ doc("PGRNseq_Demographics_DS_2015_year_birth") }}'
    - name: ethnicity
      description: '{{ doc("PGRNseq_Demographics_DS_2015_ethnicity") }}'
    - name: race
      description: '{{ doc("PGRNseq_Demographics_DS_2015_race") }}'
    - name: median_weight
      description: '{{ doc("PGRNseq_Demographics_DS_2015_median_weight") }}'
    - name: median_height
      description: '{{ doc("PGRNseq_Demographics_DS_2015_median_height") }}'
    - name: median_bmi
      description: '{{ doc("PGRNseq_Demographics_DS_2015_median_bmi") }}'
  - name: PGRNseq_ECG_DS_2015
    description: Source table for PGRNseq_ECG_DS_2015.
    columns:
    - name: subject_id
      description: '{{ doc("PGRNseq_ECG_DS_2015_subject_id") }}'
    - name: age_at_ecg
      description: '{{ doc("PGRNseq_ECG_DS_2015_age_at_ecg") }}'
    - name: ecg_qrs_duration
      description: '{{ doc("PGRNseq_ECG_DS_2015_ecg_qrs_duration") }}'
    - name: ecg_qt_interval
      description: '{{ doc("PGRNseq_ECG_DS_2015_ecg_qt_interval") }}'
    - name: ecg_qtc_bazett
      description: '{{ doc("PGRNseq_ECG_DS_2015_ecg_qtc_bazett") }}'
    - name: ecg_hr
      description: '{{ doc("PGRNseq_ECG_DS_2015_ecg_hr") }}'
    - name: ecg_pr_interval
      description: '{{ doc("PGRNseq_ECG_DS_2015_ecg_pr_interval") }}'
    - name: visit_number
      description: '{{ doc("PGRNseq_ECG_DS_2015_visit_number") }}'
  - name: PGRNseq_Labs_DS_2015
    description: Source table for PGRNseq_Labs_DS_2015.
    columns:
    - name: subject_id
      description: '{{ doc("PGRNseq_Labs_DS_2015_subject_id") }}'
    - name: age_at_lipids
      description: '{{ doc("PGRNseq_Labs_DS_2015_age_at_lipids") }}'
    - name: on_statins_at_time_of_lab
      description: '{{ doc("PGRNseq_Labs_DS_2015_on_statins_at_time_of_lab") }}'
    - name: serum_total_cholesterol
      description: '{{ doc("PGRNseq_Labs_DS_2015_serum_total_cholesterol") }}'
    - name: ldl
      description: '{{ doc("PGRNseq_Labs_DS_2015_ldl") }}'
    - name: hdl
      description: '{{ doc("PGRNseq_Labs_DS_2015_hdl") }}'
    - name: triglyceride
      description: '{{ doc("PGRNseq_Labs_DS_2015_triglyceride") }}'
    - name: visit_number
      description: '{{ doc("PGRNseq_Labs_DS_2015_visit_number") }}'
  - name: PGRNseq_SampleAttribution_DS_20171120
    description: Source table for PGRNseq_SampleAttribution_DS_20171120.
    columns:
    - name: sample_id
      description: '{{ doc("PGRNseq_SampleAttribution_DS_20171120_sample_id") }}'
    - name: analyte_type
      description: '{{ doc("PGRNseq_SampleAttribution_DS_20171120_analyte_type") }}'
  - name: PGRNseq_SampleSubjectMapping_DS_20171120
    description: Source table for PGRNseq_SampleSubjectMapping_DS_20171120.
    columns:
    - name: subject_id
      description: '{{ doc("PGRNseq_SampleSubjectMapping_DS_20171120_subject_id")
        }}'
    - name: sample_id
      description: '{{ doc("PGRNseq_SampleSubjectMapping_DS_20171120_sample_id") }}'
    - name: sample_source
      description: '{{ doc("PGRNseq_SampleSubjectMapping_DS_20171120_sample_source")
        }}'
    - name: source_sample_id
      description: '{{ doc("PGRNseq_SampleSubjectMapping_DS_20171120_source_sample_id")
        }}'
    - name: batch
      description: '{{ doc("PGRNseq_SampleSubjectMapping_DS_20171120_batch") }}'
    - name: sample_use
      description: '{{ doc("PGRNseq_SampleSubjectMapping_DS_20171120_sample_use")
        }}'
    - name: sequencing_center
      description: '{{ doc("PGRNseq_SampleSubjectMapping_DS_20171120_sequencing_center")
        }}'
  - name: PGRNseq_SubjectConsent_DS_20170412
    description: Source table for PGRNseq_SubjectConsent_DS_20170412.
    columns:
    - name: subject_id
      description: '{{ doc("PGRNseq_SubjectConsent_DS_20170412_subject_id") }}'
    - name: consent
      description: '{{ doc("PGRNseq_SubjectConsent_DS_20170412_consent") }}'
    - name: subject_source
      description: '{{ doc("PGRNseq_SubjectConsent_DS_20170412_subject_source") }}'
    - name: source_subject_id
      description: '{{ doc("PGRNseq_SubjectConsent_DS_20170412_source_subject_id")
        }}'
